version: '3'

services:
  bot:
    build: ./bot
    container_name: bot
    volumes:
      - ./bot/src:/usr/app
      - ./configuration:/usr/app/configuration
      - ./db:/usr/app/db
    depends_on:
      - db

  miniapp:
    build: ./miniapp
    container_name: miniapp
    volumes:
      - ./miniapp/src:/usr/app
      - ./configuration:/usr/app/configuration
      - ./db:/usr/app/db
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:14.3
    restart: always
    container_name: data_base
    env_file:
      - ./configuration/.env
    ports:
      - 5432:5432
volumes:
  bot:
  miniapp:
  configuration:
  db: